### ISSUE TITLE
compile uboot

### ISSUE THREAD

**Issue by gtxaspec** [BiatuAutMiahn/IVSP-T31-1.1.1-20200508#1]
how did you flash uboot from within uboot?  I can't seem to access the memory card while in the stock uboot... perhaps i am missing some commands.

**Comment by BiatuAutMiahn** [comment]
look at uEnv.txt, also the Dafang Hacks bricked uboot recovery steps. There are uboot commands that can be used to either boot into a working kernel and then flash the uboot, or load the uboot image at the appropriate memory location and then commit

Here are some references:
https://wiki.emacinc.com/wiki/Loading_Images_with_U-Boot#NAND_Flash
https://wiki.st.com/stm32mpu/wiki/U-Boot_overview#Commands

**Comment by BiatuAutMiahn** [comment]
https://wiki.st.com/stm32mpu/wiki/U-Boot_overview#Commands

**Comment by LouDnl** [comment]
Do you have v1.1.3 or zeratul release?

**Comment by BiatuAutMiahn** [comment]
I do not. I had to donate to openipc to get this release.
